@startuml actorsUseCaseDiagram
left to right direction
class equipo{
    +nombre
    +registro
}
class persona{
    +nombre
    +teléfono
    +dirección
}
class jugador{
    +Número
    +posición
}
class entrenador{
    +nivel
    +experiencia
}
class capitan{

}
class juego{
    +localidad
    +puntuacion
}
equipo<|--persona
persona<|--jugador
persona<|--entrenador
capitan<|--jugador
equipo  *--"6..19" jugador
equipo *-- "1" entrenador
equipo *-- "1" capitan 
juego o-- equipo
@enduml